default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 3 } %>
  timeout: 5000
  encoding: utf8
  reconnect: false
  host: 192.168.99.1
  port: 3306
  username: root
  password:
  encoding: utf8

development:
  <<: *default
  database: hana9_development

test:
  <<: *default
  database: hana9_test

production:
  <<: *default
  database: hana9_production
